---
title: 'Lab 2: Mask vs Covid'
author: 'Tiantian Zhao'
output: 
  pdf_document: default
  word_document: default
  html_document: default
  df_print: paged
---

```{r load packages, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(tidyverse) 
library(haven)
library(magrittr)
library(cowplot)
```

```{r clean data, echo=FALSE, warning=TRUE, message=FALSE}
raw_data <- read_csv("./mask-use/mask-use-by-county.csv")
newdata1 <- data.frame(colSums(raw_data[-1]))
names(newdata1)[1] <- "mask_use_count"
mask_use <- c("NEVER","RARELY","SOMETIMES","FREQUENTLY","ALWAYS")           
newdata1$mask_use <- mask_use 

# graph1 <- newdata1 %>%  
#   ggplot +
#   aes(x = mask_use, y = mask_use_count, fill= factor(mask_use)) +
#   geom_bar(stat='identity', position = "dodge" ) +
#   geom_text(stat='identity', aes(label=mask_use_count), vjust= 1.3, size = 2.7, position = position_dodge(width = 1)) +
#   theme_void() +
#   scale_fill_manual(values = c("bisque4", "bisque3","bisque2","bisque1", "blanchedalmond")) +
#   labs(title = "", 
#     x        = 'Mask Use Behavior',
#     y        = 'Count')
# graph1

# calculate percentage
pie_data <- newdata1 %>%
  mutate(percentage=paste0(round(mask_use_count/sum(mask_use_count)*100,2),"%"))

# create piechart
graph2 <- pie_data %>% 
  ggplot +
  aes(x="", y=mask_use_count, fill=mask_use) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y") +
  geom_text(aes(y = mask_use_count, label = percentage), color = "black", size=4.5, vjust=0.5, hjust = 0.5, position = position_stack(vjust = 0.5),) +
  scale_fill_manual("mask_use", values = c("ALWAYS"="bisque4","FREQUENTLY"= "bisque3","SOMETIMES"="bisque2","RARELY"="bisque1", "NEVER"="blanchedalmond")) +
  theme_void()+
  labs(title = "Figure 1. Mask Use Behavior Percentage", 
       subtitle = "Majority of People Always or Freqently wear a mask")
graph2

# plot_grid(graph1, graph2, labels = c('A'='Figure 1. Mask Use Behavior (by count)', 'B'='Figure 2. Mask Use Behavior (by percentile)'),
#           label_size = 9, hjust = 0, label_x = 0.01)

```


